[package]
name = "bbox-filter"
version = "0.1.0"
authors = ["Andrew Pendleton <andrew@mapbox.com>"]

[dependencies]
serde = "1.0.60"
serde_derive = "1.0.60"
serde_json = "1.0.26"
rayon = "1.0"
itertools = "0.7.8"